### PR TITLE
Add ability to use provided ConnectionPool

### PR DESCRIPTION
**Pull request by ggilder**
This is sort of a workaround to allow me to use a different Redis adapter, but seems generally worthwhile too.

@zanker @tarcieri @jkingdon

### CODE REVIEW

**Comment by jkingdon** [comment]
Looks good to me.

**Comment by tarcieri** [comment]
:thumbsup:

**Comment by ggilder** [comment]
Hmm, it looks like this actually interferes with `Service.setup_sidekiq_redis`, digging further.

**Comment by ggilder** [comment]
Just kidding, I had just misconfigured in my app. I think this patch is good to go, gonna merge and cut a release.

**Pull request merged**
